from datetime import date, datetime, time, timedelta

def _extract_time_parts(
    groupdict: dict[str, str | None],
) -> tuple[int, int, int, int]: ...
def str2datetime(s: str) -> datetime: ...
def str2date(s: str) -> date: ...
def str2time(s: str) -> time: ...
def str2timedelta(s: str) -> timedelta: ...
def timedelta2str(td: timedelta) -> str: ...
