DEBUG: bool
STATIC_DIR: str | None
CUT_TRACEBACK: bool
MAX_FETCH_COUNT: int | None
CONSOLE_WIDTH: int
SIMPLE_ALIASES: bool
INNER_JOIN_SYNTAX: bool
DEBUGGING_REMOVE_ADDR: bool
DEBUGGING_RESTORE_ESCAPES: bool
