from collections.abc import Sequence
from datetime import datetime, timedelta
from types import ModuleType
from typing import Any, ClassVar
from typing_extensions import LiteralString
from pony.orm.core import ParamKey, PyType
from pony.orm.dbapiprovider import (
    BlobConverter,
    Converter,
    DBAPIProvider,
    JsonConverter,
    RealConverter,
    StrConverter,
    TimeConverter,
    TimedeltaConverter,
    UuidConverter,
    wrap_dbapi_exceptions,
)
from pony.orm.dbschema import Column, DBSchema
from pony.orm.sqlbuilding import Param, SQLBuilder, Value
from pony.orm.sqltranslation import SQLTranslator

NoneType: type[None]
mysql_module_name: str
provider_cls: type[MySQLProvider]

def str2datetime(s: str) -> datetime | None: ...

class MySQLBlobConverter(BlobConverter):
    def sql_type(converter) -> str: ...

class MySQLBuilder(SQLBuilder):
    dialect: ClassVar[str]
    value_class: type[Value]

    def CONCAT(builder, *args) -> tuple[str, list, str]: ...
    def DATE_ADD(
        builder,
        expr: list[str],
        delta: list[(str | timedelta | ParamKey | MySQLTimedeltaConverter)],
    ) -> tuple[str, Any, str, Any, str]: ...
    def DATE_DIFF(builder, expr1, expr2) -> tuple[str, Any, str, Any, str]: ...
    def DATE_SUB(builder, expr, delta) -> tuple[str, Any, str, Any, str]: ...
    def DATETIME_ADD(builder, expr, delta) -> tuple[str, Any, str, Any, str]: ...
    def DATETIME_DIFF(builder, expr1, expr2) -> tuple[str, Any, str, Any, str]: ...
    def DATETIME_SUB(builder, expr, delta) -> tuple[str, Any, str, Any, str]: ...
    def DAY(builder, expr): ...
    def HOUR(builder, expr): ...
    def JSON_ARRAY_LENGTH(builder, value): ...
    def JSON_CONTAINS(
        builder, expr: Sequence[str], path: list[Sequence[str]], key: Sequence
    ) -> list[str | Param | Value | Any]: ...
    def JSON_EQ(builder, left, right): ...
    def JSON_NE(builder, left, right): ...
    def JSON_NONZERO(builder, expr): ...
    def JSON_PARAM(builder, expr): ...
    def JSON_QUERY(builder, expr, path): ...
    def JSON_VALUE(builder, expr, path, type): ...
    def LTRIM(builder, expr, chars=...): ...
    def MINUTE(builder, expr): ...
    def MONTH(builder, expr): ...
    def RTRIM(builder, expr, chars=...): ...
    def SECOND(builder, expr): ...
    def TO_INT(builder, expr): ...
    def TO_REAL(builder, expr): ...
    def TO_STR(builder, expr): ...
    def TRIM(
        builder, expr: list[str], chars: list[str | tuple | StrConverter] | None = None
    ) -> (
        tuple[str, list[str], str] | tuple[str, list[str], str, Value | Param, str]
    ): ...
    @classmethod
    def wrap_param_to_json_array(cls, values): ...
    def YEAR(builder, expr): ...

class MySQLColumn(Column):
    auto_template: ClassVar[str | None]

class MySQLJsonConverter(JsonConverter):
    EQ: ClassVar[LiteralString]
    NE: ClassVar[LiteralString]

    def init(self, kwargs): ...

class MySQLProvider(DBAPIProvider):
    converter_classes: list[
        tuple[PyType | type[None] | tuple[type[int]], type[Converter]]  # noqa: Y090
    ]
    dbapi_module: ModuleType
    dbschema_cls: type[MySQLSchema]
    default_time_precision: int
    dialect: str
    fk_types: dict[str, str]
    index_if_not_exists_syntax: bool
    max_name_len: int
    max_params_count: int
    paramstyle: str
    quote_char: str
    sqlbuilder_cls: type[SQLBuilder]
    table_if_not_exists_syntax: bool
    translator_cls: type[SQLTranslator]
    uint64_support: bool
    varchar_default_max_len: int | None

    def fk_exists(provider, connection, table_name, fk_name, case_sensitive=...): ...
    def get_pool(provider, *args, **kwargs): ...
    def index_exists(
        provider, connection, table_name, index_name, case_sensitive=...
    ): ...
    @wrap_dbapi_exceptions
    def inspect_connection(provider, connection): ...
    def normalize_name(provider, name): ...
    @wrap_dbapi_exceptions
    def release(provider, connection, cache=...): ...
    @wrap_dbapi_exceptions
    def set_transaction_mode(provider, connection, cache): ...
    def should_reconnect(provider, exc): ...
    def table_exists(provider, connection, table_name, case_sensitive=...): ...

class MySQLRealConverter(RealConverter):
    def sql_type(converter) -> str: ...

class MySQLSchema(DBSchema):
    column_class: ClassVar[type[Column]]
    dialect: ClassVar[str]
    inline_fk_syntax: ClassVar[bool]

class MySQLStrConverter(StrConverter):
    def sql_type(converter) -> str: ...

class MySQLTimeConverter(TimeConverter):
    def sql2py(converter, val): ...

class MySQLTimedeltaConverter(TimedeltaConverter):
    sql_type_name: LiteralString

class MySQLTranslator(SQLTranslator):
    dialect: ClassVar[str]
    json_path_wildcard_syntax: ClassVar[bool]

class MySQLUuidConverter(UuidConverter):
    def sql_type(converter) -> str: ...

class MySQLValue(Value): ...
