from collections.abc import Iterable, Sequence
import cx_Oracle  # type: ignore

from datetime import timedelta
from re import Pattern
from types import ModuleType
from typing import Any, ClassVar
from typing_extensions import LiteralString
from pony.orm.core import DbConnection, ParamKey, PyType, TableName
from pony.orm.dbapiprovider import (
    BlobConverter,
    BoolConverter,
    Converter,
    DBAPIProvider,
    DateConverter,
    DatetimeConverter,
    DecimalConverter,
    IntConverter,
    JsonConverter,
    Pool,
    RealConverter,
    StrConverter,
    TimeConverter,
    TimedeltaConverter,
    UuidConverter,
    wrap_dbapi_exceptions,
)
from pony.orm.dbschema import Column, DBObject, DBSchema, Table
from pony.orm.sqlbuilding import Param, SQLBuilder, Value
from pony.orm.sqltranslation import ConstMonad, NoneMonad, SQLTranslator

json_item_re: Pattern[str]
NoneType: type[None]
provider_cls: type[OraProvider]
trigger_template: LiteralString

def get_inputsize(arg) -> cx_Oracle.DATETIME | None: ...
def output_type_handler(cursor, name, defaultType, size, precision, scale): ...
def set_input_sizes(cursor, arguments) -> None: ...
def to_int_or_decimal(val): ...
def to_decimal(val): ...

class OraBlobConverter(BlobConverter):
    def sql2py(converter, val): ...

class OraBoolConverter(BoolConverter):
    def py2sql(converter, val): ...
    def sql2py(converter, val): ...
    def sql_type(converter) -> str: ...

class OraBuilder(SQLBuilder):
    dialect: ClassVar[str]
    json_value_type_mapping: dict[type, str]

    def build_json_path(
        builder, path: list[list[(str | int | ParamKey | Converter)]]
    ) -> tuple[Param | Value, bool, bool]: ...
    def DATE(builder, expr: Sequence[str | list[str]]) -> tuple[str, Any, str]: ...
    def DATE_ADD(
        builder,
        expr: list[str],
        delta: list[(str | timedelta | ParamKey | OraTimedeltaConverter)],
    ) -> tuple[str, Any, str, Any, str]: ...
    def DATE_DIFF(builder, expr1, expr2) -> tuple[str, Any, str, Any, str]: ...
    def DATE_SUB(builder, expr, delta) -> tuple[str, Any, str, Any, str]: ...
    def DATETIME_ADD(builder, expr, delta) -> tuple[str, Any, str, Any, str]: ...
    def DATETIME_DIFF(builder, expr1, expr2) -> tuple[str, Any, str, Any, str]: ...
    def DATETIME_SUB(builder, expr, delta) -> tuple[str, Any, str, Any, str]: ...
    def GROUP_CONCAT(builder, distinct, expr, sep=...): ...
    def INSERT(
        builder,
        table_name: str,
        columns: Iterable[str | Iterable],
        values: Iterable[Sequence[str | tuple[int, None, None] | Converter]],
        returning: str | None = None,
    ) -> Sequence[str | list[str]]: ...
    def JSON_ARRAY_LENGTH(builder, value): ...
    def JSON_CONTAINS(builder, expr, path, key): ...
    def JSON_NONZERO(builder, expr): ...
    def JSON_QUERY(builder, expr, path): ...
    def JSON_VALUE(builder, expr, path, type): ...
    def LIMIT(builder, limit, offset=...): ...
    def MOD(builder, a, b): ...
    def RANDOM(builder): ...
    def ROWID(builder, *expr_list): ...
    def SELECT(
        builder, *sections: Sequence[str | list[str]]
    ) -> Sequence[str | Sequence[str | list[str]]]: ...
    def SELECT_FOR_UPDATE(
        builder, nowait: bool, skip_locked: bool, *sections: Sequence[str | list[str]]
    ) -> tuple[Sequence[str | Sequence[str | list[str]]], str, str, str, str]: ...
    def TO_REAL(builder, expr): ...
    def TO_STR(builder, expr): ...

class OraColumn(Column):
    auto_template: ClassVar[str | None]

class OraConstMonad(ConstMonad):
    @staticmethod
    def new(value): ...

class OraDateConverter(DateConverter):
    def sql2py(converter, val): ...

class OraDatetimeConverter(DatetimeConverter):
    sql_type_name: LiteralString

class OraDecimalConverter(DecimalConverter):
    def sql_type(converter) -> str: ...

class OraIntConverter(IntConverter):
    signed_types: dict[int | None, str]
    unsigned_types: dict[int | None, str] | None

    def init(self, kwargs): ...

class OraJsonConverter(JsonConverter):
    json_kwargs: ClassVar[dict[str, Any]]
    optimistic: ClassVar[bool]

    def sql2py(converter, dbval): ...
    def sql_type(converter) -> str: ...

class OraNoneMonad(NoneMonad):
    def __init__(monad, value=...) -> None: ...

class OraPool(Pool):
    cx_pool: cx_Oracle.SessionPool
    forked_pools: list[tuple[cx_Oracle.SessionPool, int]]
    kwargs: dict[str, Any]
    pid: int

    def __init__(pool, **kwargs) -> None: ...
    def connect(pool): ...
    def disconnect(pool): ...
    def drop(pool, con): ...
    def release(pool, con): ...

class OraProvider(DBAPIProvider):
    converter_classes: list[
        tuple[PyType | type[None] | tuple[type[int]], type[Converter]]  # noqa: Y090
    ]
    dbapi_module: ModuleType
    dbschema_cls: type[DBSchema]
    dialect: str
    index_if_not_exists_syntax: bool
    max_name_len: int
    name_before_table: str
    paramstyle: str
    sqlbuilder_cls: type[OraBuilder]
    table_if_not_exists_syntax: bool
    translator_cls: type[OraTranslator]
    uint64_support: bool
    varchar_default_max_len: int | None

    def drop_table(provider, connection, table_name): ...
    @wrap_dbapi_exceptions
    def execute(provider, cursor, sql, arguments=..., returning_id=...): ...
    def fk_exists(provider, connection, table_name, fk_name, case_sensitive=...): ...
    def get_pool(provider, *args, **kwargs): ...
    def index_exists(
        provider, connection, table_name, index_name, case_sensitive=...
    ): ...
    @wrap_dbapi_exceptions
    def inspect_connection(provider, connection): ...
    def normalize_name(provider, name): ...
    def normalize_vars(provider, vars, vartypes): ...
    @wrap_dbapi_exceptions
    def set_transaction_mode(provider, connection, cache): ...
    def should_reconnect(provider, exc): ...
    def table_exists(provider, connection, table_name, case_sensitive=...): ...
    def table_has_data(provider, connection, table_name): ...

class OraRealConverter(RealConverter):
    def sql_type(converter) -> str: ...

class OraSchema(DBSchema):
    column_class: ClassVar[type[Column]]
    dialect: ClassVar[str]
    table_class: ClassVar[type[Table]]

class OraSequence(DBObject):
    name: TableName
    table: OraTable
    typename: ClassVar[str]

    def __init__(sequence, table: OraTable, name: TableName | None = None) -> None: ...
    def exists(
        sequence,
        provider: OraProvider,
        connection: DbConnection,
        case_sensitive: bool = True,
    ): ...
    def get_create_command(sequence): ...

class OraStrConverter(StrConverter):
    def sql2py(converter, val): ...
    def sql_type(converter) -> str: ...
    def validate(converter, val, obj=...): ...

class OraTable(Table):
    def get_objects_to_create(table, created_tables=...): ...

class OraTimedeltaConverter(TimedeltaConverter):
    sql_type_name: LiteralString

    def __init__(converter, provider, py_type, attr=...) -> None: ...

class OraTimeConverter(TimeConverter):
    sql_type_name: LiteralString

    def __init__(converter, provider, py_type, attr=...) -> None: ...
    def py2sql(converter, val): ...
    def sql2py(converter, val): ...

class OraTranslator(SQLTranslator):
    ConstMonad: type[OraConstMonad]
    NoneMonad: type[OraNoneMonad]
    dialect: ClassVar[str]
    json_path_wildcard_syntax: ClassVar[bool]
    json_values_are_comparable: ClassVar[bool]
    rowid_support: ClassVar[bool]

class OraTrigger(DBObject):
    typename: ClassVar[str]

    def __init__(trigger, table, column, sequence) -> None: ...
    def exists(trigger, provider, connection, case_sensitive=...): ...
    def get_create_command(trigger): ...

class OraUuidConverter(UuidConverter):
    def sql_type(converter) -> str: ...
