from ast import Lambda, expr
from collections import defaultdict
from collections.abc import Callable, Iterable
from datetime import datetime
from io import BytesIO
from itertools import count as _count
from types import CodeType, ModuleType, TracebackType
from typing import Any, ClassVar, NoReturn, TypeVar, overload
from xml.etree.ElementTree import Element

from typing_extensions import TypeAlias

from pony.orm.core import EntityProxy, OptAttrValue, Query, SetInstance

localbase: TypeAlias = object  # noqa: Y042

_T = TypeVar("_T")
_KT = TypeVar("_KT")
_VT = TypeVar("_VT")

cut_traceback_depth: int

def absolutize_path(filename: str, frame_depth: int) -> str: ...
def avg(iter: Iterable[float]) -> float | None: ...
def between(x: Any, a: Any, b: Any) -> bool: ...
def coalesce(*args) -> OptAttrValue: ...
def concat(*args) -> str: ...
def copy_ast(tree: expr) -> expr: ...
@overload
def count() -> _count[int]: ...
@overload
def count(args: tuple, kwargs: dict) -> _count: ...
@overload
def count(args: tuple) -> _count: ...
@overload
def count(arg: Iterable | SetInstance | Query) -> int: ...
def cut_traceback(func: Callable) -> Callable: ...
def datetime2timestamp(d: datetime) -> str: ...
def decorator(caller: Callable, func: Callable | None = None) -> Callable: ...
def deduplicate(value: _T, deduplication_cache: dict[type[_T], dict[_T, _T]]) -> _T: ...
def deprecated(stacklevel: int, message: str) -> None: ...
def deref_proxy(value: EntityProxy | Any) -> Any: ...
def distinct(iter: Iterable[_T]) -> defaultdict[_T, int]: ...
def get_codeobject_id(codeobject: CodeType) -> int: ...
def get_lambda_args(func: Callable | Lambda) -> list[str]: ...
def group_concat(items: Iterable | None, sep: str = ",") -> str | None: ...
def import_module(name: str) -> ModuleType: ...
def is_absolute_path(filename: str) -> bool: ...
def is_ident(string: str) -> bool: ...
def is_utf8(encoding: str) -> bool: ...
def parse_expr(s: str, pos: int = 0) -> tuple[str, bool]: ...
def pickle_ast(val: expr) -> BytesIO: ...
def reraise(
    exc_type: type[BaseException] | None,
    exc: BaseException | None,
    tb: TracebackType | None,
) -> NoReturn: ...
@overload
def strjoin(
    sep: str,
    strings: Iterable[str],
    source_encoding: str = "ascii",
    dest_encoding: None = None,
) -> str: ...
@overload
def strjoin(
    sep: str,
    strings: Iterable[str],
    source_encoding: str = "ascii",
    *,
    dest_encoding: str,
) -> bytes: ...
def throw(exc_type: type[Exception] | Exception, *args, **kwargs) -> NoReturn: ...
def timestamp2datetime(t: str) -> datetime: ...
def tostring(x: str | bytes | Element) -> str: ...
def truncate_repr(s: object, max_len: int = 100) -> str: ...
def unpickle_ast(pickled: BytesIO) -> expr: ...

class PonyDeprecationWarning(DeprecationWarning): ...

def _hashable_wrap(func: Callable) -> Callable: ...

class HashableDict(dict[_KT, _VT]):
    _hash: int

    __setitem__: ClassVar[Callable]
    __delitem__: ClassVar[Callable]
    clear: ClassVar[Callable]
    pop: ClassVar[Callable]
    popitem: ClassVar[Callable]
    setdefault: ClassVar[Callable]
    update: ClassVar[Callable]

    def __deepcopy__(
        self,
        memo: dict[int, object],
    ) -> HashableDict[_KT, _VT]: ...

    # "__hash__()" overrides ClassVar of same name in class "dict"
    def __hash__(self) -> int: ...  # type: ignore
