from ast import (
    Assign,
    Attribute,
    BinOp,
    BoolOp,
    Bytes,
    Call,
    Compare,
    Constant,
    Dict,
    FormattedValue,
    GeneratorExp,
    IfExp,
    JoinedStr,
    List,
    Name,
    NameConstant,
    Num,
    Slice,
    Str,
    Subscript,
    Tuple,
    UnaryOp,
    cmpop,
    comprehension,
    expr,
    keyword,
    operator,
)
from collections import defaultdict
from collections.abc import Callable, Generator, Iterable
from types import CellType, CodeType
from typing import Any, overload

from typing_extensions import LiteralString, TypeAlias

_ConstValue: TypeAlias = str | bytes | bool | int | float | complex | None

operator_mapping: dict[LiteralString, type[cmpop]]
ast_cache: dict[int, tuple[expr, set[str]]]

def binop(node_type: type[operator]) -> Callable: ...
@overload
def clean_assign(node: Name) -> Name: ...
@overload
def clean_assign(node: Assign) -> list[expr]: ...
def decompile(
    x: CodeType | Generator | Callable,
) -> tuple[expr, set[str], dict[str, CellType]]: ...
def is_const(
    value: _ConstValue | tuple[_ConstValue, ...] | tuple[tuple, ...],
) -> bool: ...
def make_const(
    value: _ConstValue | tuple[_ConstValue, ...] | tuple[tuple, ...],
) -> Constant | Num | Str | Bytes | Tuple | NameConstant: ...
def simplify(clause: expr) -> expr: ...

class DecompileError(NotImplementedError): ...

class Decompiler:
    abs_jump_to_top: int
    ast: expr
    assnames: set[str]
    code: CodeType
    conditions_end: int
    end: int
    external_names: set[str]
    for_iter_pos: int
    instructions: list[tuple[int, int, str, list[int]]]
    instructions_map: dict[int, int]
    jump_map: defaultdict[int, list[int]]
    kw_names: Iterable[str] | None
    names: set[str]
    next_pos: int
    or_jumps: set[int]
    pos: int
    stack: list[expr]
    start: int
    targets: dict[int, expr]

    def __init__(
        decompiler, code: CodeType, start: int = 0, end: int | None = None
    ) -> None: ...
    def _call_function(
        decompiler,
        args: Iterable[expr],
        keywords: Iterable[keyword] | None = None,
    ) -> GeneratorExp | Call: ...
    def analyze_jumps(decompiler) -> None: ...
    def conditional_jump(decompiler, endpos: int, if_true: bool) -> BoolOp: ...
    def conditional_jump_old(decompiler, endpos: int, if_true: bool) -> BoolOp: ...
    def conditional_jump_new(decompiler, endpos: int, if_true: bool) -> BoolOp: ...
    def conditional_jump_none_impl(decompiler, endpos: int, negate: bool) -> BoolOp: ...
    def decompile(decompiler) -> None: ...
    def get_instructions(decompiler) -> None: ...
    def jump_if_none(decompiler, endpos: int) -> BoolOp: ...
    def jump_if_not_none(decompiler, endpos: int) -> BoolOp: ...
    def pop_items(decompiler, size: int) -> list[expr]: ...
    def process_target(decompiler, pos: int | None, partial: bool = False) -> None: ...
    def store(decompiler, node: Name | Assign) -> None: ...
    def BINARY_OP(decompiler, opcode: int) -> BinOp | Name: ...
    def BINARY_SUBSCR(decompiler) -> Subscript: ...
    def BUILD_CONST_KEY_MAP(decompiler, length: int) -> Dict: ...
    def BUILD_LIST(decompiler, size: int) -> List: ...
    def BUILD_MAP(decompiler, length: int) -> Dict: ...
    def BUILD_SLICE(decompiler, size: int) -> Slice: ...
    def BUILD_STRING(decompiler, count: int) -> JoinedStr: ...
    def BUILD_TUPLE(decompiler, size: int) -> Tuple: ...
    def CACHE(decompiler) -> None: ...
    def CALL(decompiler, argc: int) -> Call | GeneratorExp: ...
    def CALL_FUNCTION_EX(decompiler, argc: int) -> Call | GeneratorExp: ...
    def COMPARE_OP(decompiler, op: str) -> Compare: ...
    def CONTAINS_OP(decompiler, invert: int) -> Compare: ...
    def COPY_FREE_VARS(decompiler, n: int) -> None: ...
    def FORMAT_VALUE(decompiler, flags: int) -> FormattedValue: ...
    def FOR_ITER(decompiler, endpos: int) -> comprehension: ...
    def GET_ITER(decompiler) -> None: ...
    def IS_OP(decompiler, invert: int) -> Compare: ...
    def JUMP_FORWARD(decompiler, endpos: int) -> IfExp: ...
    def JUMP_IF_FALSE(decompiler, endpos: int) -> BoolOp: ...
    def JUMP_IF_TRUE(decompiler, endpos: int) -> BoolOp: ...
    def KW_NAMES(decompiler, kw_names: Iterable[str]) -> None: ...
    def LIST_APPEND(decompiler, offset: int): ...
    def LIST_EXTEND(decompiler, offset: int) -> List: ...
    def LOAD_ATTR(decompiler, attr_name: str, push_null: bool) -> Attribute: ...
    def LOAD_CLOSURE(decompiler, freevar: str) -> Name: ...
    def LOAD_CONST(
        decompiler,
        const_value: _ConstValue | tuple[_ConstValue, ...] | tuple[tuple, ...],
    ) -> Constant | Num | Str | Bytes | Tuple | NameConstant: ...
    def LOAD_DEREF(decompiler, freevar: str) -> Name: ...
    def LOAD_FAST(decompiler, varname: str) -> Name: ...
    def LOAD_GLOBAL(decompiler, varname: str, push_null: int) -> Name: ...
    def LOAD_METHOD(decompiler, methname: str) -> Attribute: ...
    def MAKE_CELL(decompiler, freevar: str) -> None: ...
    def MAKE_FUNCTION(decompiler, argc: int) -> expr: ...
    def POP_JUMP_IF_NONE(decompiler, endpos: int) -> BoolOp: ...
    def POP_JUMP_IF_NOT_NONE(decompiler, endpos: int) -> BoolOp: ...
    def POP_TOP(decompiler) -> None: ...
    def PRECALL(decompiler, argc: int) -> None: ...
    def PUSH_NULL(decompiler) -> None: ...
    def RESUME(decompiler, where: int) -> None: ...
    def RETURN_GENERATOR(decompiler) -> None: ...
    def RETURN_VALUE(decompiler) -> expr: ...
    def STORE_DEREF(decompiler, freevar: str) -> None: ...
    def STORE_FAST(decompiler, varname: str) -> None: ...
    def UNARY_NEGATIVE(decompiler) -> UnaryOp: ...
    def UNARY_NOT(decompiler) -> UnaryOp: ...
    def UNPACK_SEQUENCE(decompiler, count: int) -> Assign: ...
    def YIELD_VALUE(decompiler, _: None = None) -> GeneratorExp: ...

class InvalidQuery(Exception): ...
